//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telCom_2._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance1
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> DateEvent { get; set; }
        public Nullable<double> Summa { get; set; }
        public string TextEvent { get; set; }
    }
}
