//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telCom_2._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementsTariff1
    {
        public int Id { get; set; }
        public Nullable<int> TariffId { get; set; }
        public Nullable<int> CityFromId { get; set; }
        public Nullable<int> CityToId { get; set; }
        public Nullable<double> CostCall { get; set; }
    }
}
