//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telCom_2._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEntity1
    {
        public int Id { get; set; }
        public string AddressCompany { get; set; }
        public string Bik { get; set; }
        public string Inn { get; set; }
        public Nullable<int> CoressAccount { get; set; }
        public string FaceCharge { get; set; }
        public string Name { get; set; }
    }
}
