//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telCom_2._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person1
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
